title: FORMAWEB IV
author: nunhes
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
email: nunhes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Repositorio de lecturas e exercicios para o Programa de Emprego Fomaweb IV.
  Concello de Vigo. 2021-2022.

# social links
twitter_username: nunhes # DO NOT include the @ character, or else the build will fail!
github_username:  nunhes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
